In [1]:
import numpy as np

# Define a square matrix
matrix = np.array([[2, 1],
                   [1, 3]])

# Define the exponent
power = 3

# Perform matrix exponentiation
result = np.linalg.matrix_power(matrix, power)

print("Original Matrix:")
print(matrix)
print(f"Matrix raised to the power {power}:")
print(result)


Original Matrix:
[[2 1]
 [1 3]]
Matrix raised to the power 3:
[[15 20]
 [20 35]]


In [2]:
negative_power = -1
result_negative = np.linalg.matrix_power(matrix, negative_power)

print(f"Matrix raised to the power {negative_power}:")
print(result_negative)


Matrix raised to the power -1:
[[ 0.6 -0.2]
 [-0.2  0.4]]
